// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {api} from '../models';

export function AddTorrentByHash(arg1:string):Promise<string>;

export function AddTorrentByMeta(arg1:string):Promise<main.TorrentAddResult>;

export function CheckHeader(arg1:string):Promise<boolean>;

export function CreateTorrent(arg1:string,arg2:string):Promise<main.TorrentCreateResult>;

export function ExportMeta(arg1:string):Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetFiles(arg1:string):Promise<Array<api.File>>;

export function GetInfo(arg1:string):Promise<api.TorrentInfo>;

export function GetPeers(arg1:string):Promise<Array<api.Peer>>;

export function GetPlainFiles(arg1:string):Promise<Array<api.PlainFile>>;

export function GetSpeedLimit():Promise<api.SpeedLimits>;

export function GetTorrents():Promise<Array<api.Torrent>>;

export function IsDarkTheme():Promise<boolean>;

export function OpenDir():Promise<string>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenFolderSelectFile(arg1:string):Promise<void>;

export function RemoveTorrent(arg1:string,arg2:boolean,arg3:boolean):Promise<string>;

export function SaveConfig(arg1:string,arg2:boolean,arg3:boolean,arg4:string,arg5:string,arg6:string):Promise<string>;

export function SetActive(arg1:string,arg2:boolean):Promise<string>;

export function SetSpeedLimit(arg1:number,arg2:number):Promise<string>;

export function ShowMsg(arg1:string):Promise<void>;

export function ShowWarnMsg(arg1:string):Promise<void>;

export function StartDownload(arg1:string,arg2:Array<string>):Promise<void>;

export function SwitchTheme():Promise<void>;

export function Throw(arg1:Error):Promise<void>;

export function WaitReady():Promise<void>;

export function WantRemoveTorrent(arg1:Array<string>):Promise<void>;
