// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrentByHash(arg1) {
  return window['go']['main']['App']['AddTorrentByHash'](arg1);
}

export function CheckHeader(arg1) {
  return window['go']['main']['App']['CheckHeader'](arg1);
}

export function GetFiles(arg1) {
  return window['go']['main']['App']['GetFiles'](arg1);
}

export function GetTorrents() {
  return window['go']['main']['App']['GetTorrents']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function RemoveTorrent(arg1, arg2) {
  return window['go']['main']['App']['RemoveTorrent'](arg1, arg2);
}

export function SetActive(arg1, arg2) {
  return window['go']['main']['App']['SetActive'](arg1, arg2);
}
