// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrentByHash(arg1) {
  return window['go']['main']['App']['AddTorrentByHash'](arg1);
}

export function AddTorrentByMeta(arg1) {
  return window['go']['main']['App']['AddTorrentByMeta'](arg1);
}

export function CheckHeader(arg1) {
  return window['go']['main']['App']['CheckHeader'](arg1);
}

export function CheckOpenedFile() {
  return window['go']['main']['App']['CheckOpenedFile']();
}

export function CreateTorrent(arg1, arg2) {
  return window['go']['main']['App']['CreateTorrent'](arg1, arg2);
}

export function ExportMeta(arg1) {
  return window['go']['main']['App']['ExportMeta'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFiles(arg1) {
  return window['go']['main']['App']['GetFiles'](arg1);
}

export function GetInfo(arg1) {
  return window['go']['main']['App']['GetInfo'](arg1);
}

export function GetPeers(arg1) {
  return window['go']['main']['App']['GetPeers'](arg1);
}

export function GetPlainFiles(arg1) {
  return window['go']['main']['App']['GetPlainFiles'](arg1);
}

export function GetSpeedLimit() {
  return window['go']['main']['App']['GetSpeedLimit']();
}

export function GetTorrents() {
  return window['go']['main']['App']['GetTorrents']();
}

export function OpenDir() {
  return window['go']['main']['App']['OpenDir']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenFolderSelectFile(arg1) {
  return window['go']['main']['App']['OpenFolderSelectFile'](arg1);
}

export function RemoveTorrent(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveTorrent'](arg1, arg2, arg3);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SetActive(arg1, arg2) {
  return window['go']['main']['App']['SetActive'](arg1, arg2);
}

export function SetSpeedLimit(arg1, arg2) {
  return window['go']['main']['App']['SetSpeedLimit'](arg1, arg2);
}

export function ShowMsg(arg1) {
  return window['go']['main']['App']['ShowMsg'](arg1);
}

export function StartDownload(arg1, arg2) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2);
}

export function Throw(arg1) {
  return window['go']['main']['App']['Throw'](arg1);
}

export function WantRemoveTorrent(arg1) {
  return window['go']['main']['App']['WantRemoveTorrent'](arg1);
}
